package com.example.crudv1.navigation

sealed class AppScreens(val ruta:String) {
    object MenuInicio : AppScreens("MenuInicio")
    object MenuInicio2 : AppScreens("MenuInicio2")
    object MenuInicio3 : AppScreens("MenuInicio3")
    object Inicio : AppScreens("Inicio")
    object ClienteInforme : AppScreens("ClienteInforme")
    object ClienteConsultar : AppScreens("ClienteConsultar")
    object ClienteModificar: AppScreens("ClienteModificar")
    object ClienteGuardar : AppScreens("ClienteGuardar")
    object ClienteBorrar : AppScreens("ClienteBorrar")
    object VendedorInforme : AppScreens("VendedorInforme")
    object VendedorConsultar : AppScreens("VendedorConsultar")
    object VendedorModificar: AppScreens("VendedorModificar")
    object VendedorGuardar : AppScreens("VendedorGuardar")
    object VendedorBorrar : AppScreens("VendedorBorrar")
    object EntrenadorInforme : AppScreens("EntrenadorInforme")
    object EntrenadorConsultar : AppScreens("EntrenadorConsultar")
    object EntrenadorModificar: AppScreens("EntrenadorModificar")
    object EntrenadorGuardar : AppScreens("EntrenadorGuardar")
    object EntrenadorBorrar : AppScreens("EntrenadorBorrar")
    object InicioSesion : AppScreens("InicioSesion")
    object Inicio2 : AppScreens("Inicio2")
    object Campos : AppScreens("Campos")
    object Piscina : AppScreens("Piscina")
    object BorrarReserva : AppScreens("BorrarReserva")
    object CambiarReserva : AppScreens("CambiarReserva")
    object PiscinaCerrada : AppScreens("PiscinaCerrada")
    object Gimnasio : AppScreens("Gimnasio")
    object StepFuncional : AppScreens("StepFuncional")
    object ReservaStep : AppScreens("ReservaStep")
    object Clases : AppScreens("Clases")
    object ReservaClases : AppScreens("ReservaClases")
    object MostrarReservasGym : AppScreens("MostrarReservasGym")
    object MostrarReservas : AppScreens("MostrarReservas")
    object Bike : AppScreens("Bike")
    object Health : AppScreens("Health")
    object Aqua : AppScreens("Aqua")
    object Fitness : AppScreens("Fitness")
    object Yoga : AppScreens("Yoga")
    object Ejercicios : AppScreens("Ejercicios")
    object MostrarReservas2 : AppScreens("MostrarReservas2")
    object Puntos : AppScreens("Puntos")
    object Futbol : AppScreens("Futbol")
    object ReservasFutbol : AppScreens("ReservasFutbol")




}